---
title: Lisa Marie Runfola
description: Lisa Marie is your life ignitor and podcast host. She’s a woman with a degree in CS (common sense, not computer science) who has experienced euphoric highs and agonizing lows on her journey. Grand leaps of faith have led her to the full life she leads today, and one of her missions is to share with others how she was able to pull herself out. If she can do it, so can you.
image: "/LMRA_Website-SocialPreview.jpeg"
timezone: Asia/Kolkata
collections:
  blog:
    title: Blog
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: posts
    type: posts
  values:
    layout: default
    permalink: "/:title/"
- scope:
    path: work
    type: posts
  values:
    layout: layout--work
    permalink: "/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
  values:
    layout: default
description: Lisa Marie is your life ignitor and podcast host. She’s a woman with
  a degree in CS (common sense, not computer science) who has experienced euphoric
  highs and agonizing lows on her journey. Grand leaps of faith have led her to the
  full life she leads today, and one of her missions is to share with others how she
  was able to pull herself out. If she can do it, so can you.
image: LMRA_Website-SocialPreview.jpeg
url: http://lisamarierunfola.com
baseurl: 
permalink: pretty
exclude:
- ".git"
- ".gitignore"
- ".DS_Store"
- ".sass-cache"
- package.json
- Gruntfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- LICENSE
